language: cpp
os:
  - linux
compiler:
  - gcc

before_install:
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe multiverse"
  - sudo apt-get update

install:
  - sudo apt-get install --no-install-recommends libnetcdfc7
  - sudo apt-get install --no-install-recommends gfortran libnetcdf-dev python-numpy python-cffi python-pytest
  - wget http://www2.mmm.ucar.edu/wrf/src/WRFV3.6.1.TAR.gz
  - tar xvzf WRFV3.6.1.TAR.gz

script:
  - mkdir build
  - cd build
  - WRF_SRC_PATH=../WRFV3 cmake ..
  - make
  - make test || cat Testing/Temporary/LastTest.log / # "/" intentional! (just to make cat exit with an error code)
